### ISSUE TITLE
Sporadic Error when using CLI

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/NAMCr#12]
@David-Fowler I am getting this error when I try and use the CLI in R. I have gotten the same error sporadically over the last few weeks. Yesterday I got this error a few times. I restarted R Studio a few times and then it went away and all was well again. I was able to make API calls and get data back.

Any ideas please?

<img width="774" alt="Screen Shot 2021-08-18 at 10 23 59 AM" src="https://user-images.githubusercontent.com/8645379/129944174-a061f282-7e48-4602-8ef5-34a99389f314.png">

**Comment by philipbaileynar** [comment]
It just failed a whole bunch of times in a row. Left it 20 minutes and tried it again and now it works.... Sorry, I know that this is the worst kind of bug report.

**Comment by David-Fowler** [comment]
This will be fixed in the update pushed later tonight. It is mixed in with other fixes regarding the new API. This particular issue I believe revolves around credentials and key timeouts but I am not 100% certain. I have added a unit test to attempt to catch this type of issue from here on out.

**Comment by philipbaileynar** [comment]
This is really frustrating. I can't use NAMCr at all while this is outstanding.

**Comment by David-Fowler** [comment]
I will dig out time tonight to get the update out.

**Comment by David-Fowler** [comment]
@philipbaileynar if this is still occurring for you can you try the following to narrow the issue down for me. I have already checked the credential timeout code as well as a few other targeted sections with no luck in regenerating the issue. Closing R studio and reopening (unless you have cached your workspace) should have set the package state similar to the second command below. If you could test the cli() function after each of the following lines of code it may help. 

```
NAMCr::diagnose_connection()
# Make sure the output reads:
# Internet, API and oAuth2 provider are all available and online.

NAMCr::reinitialize()
# test the cli()
cli()

NAMCr::reinitialize(clear_credentials = TRUE)
# test the cli()
cli()
```

**Comment by philipbaileynar** [comment]
<img width="499" alt="Screen Shot 2021-09-03 at 12 45 24 PM" src="https://user-images.githubusercontent.com/8645379/132058446-9e705f11-2cfa-4d65-a4cc-7c1ef9869710.png">

**Comment by David-Fowler** [comment]
Well that is no good... looks like I never fully hooked up the diagnose_connection function. The latest version, 0.5.5, has the fix for the diagnose_connection function. This was just pushed.

**Comment by philipbaileynar** [comment]
I upgraded to 0.5.5. 

CLI worked. I will report back here if the "vector size" error happens again.
