### ISSUE TITLE
Error Retrieving ModelInfo

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/NAMCr#13]
I am trying to retrieve the modelInfo for a single model. Note this does include a potentially sizeable GeoJSON object.

In insomnia (i.e. the API is working):

<img width="1188" alt="Screen Shot 2021-10-01 at 2 51 49 PM" src="https://user-images.githubusercontent.com/8645379/135690044-407e151a-d1b3-4d45-b393-f8de185e5538.png">

In NAMCr:

<img width="801" alt="Screen Shot 2021-10-01 at 2 52 32 PM" src="https://user-images.githubusercontent.com/8645379/135690100-8d1d8973-a4cf-4df6-a1b0-fe17be28aa66.png">

**Comment by David-Fowler** [comment]
Will look into this and get back to you
