### ISSUE TITLE
0.7.1 CLI error

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/NAMCr#18]
Help please

<img width="1764" alt="Screen Shot 2021-11-17 at 3 10 51 PM" src="https://user-images.githubusercontent.com/8645379/142297240-d52f1f47-0724-402f-ab22-77f2b79b3df3.png">

**Comment by David-Fowler** [comment]
This was introduced in the latest API push. I am aware of the problems but the large push to this package will fix it and prevent major / minor API adjustments from breaking the introspection mapping in the future. I will have this out later tonight.
FYI @courtwrightj01 , @Feldspar5

**Comment by courtwrightj01** [comment]
This error occurs for every query I do. Please push a new version of NAMCr ASAP.

**Comment by philipbaileynar** [comment]
This is fixed with version 0.7.2
