### ISSUE TITLE
Missing records at end of datasets

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/NAMCr#19]
NAMCr is always returning a round number of records and appears to be missing the last rows of each request.

Predictors example:

- There are 180 predictors in the database.
- The API returns 180 records.
- NAMCr returns 100 records.

Similar things are happening with other endpoints. The evidence that something is amiss is that the number of records returns by NAMCr always appear in the round hundreds.

Perhaps when NAMCr gets back fewer records than the requested limit it is forgetting to append these to the data frame?

FYI @Feldspar5 @courtwrightj01

**Comment by MattReimer** [comment]
I think this is the same issue as #20 See the note I left there with a theory why this might be happening.

**Comment by David-Fowler** [comment]
fixed in version 0.7.3

**Comment by philipbaileynar** [comment]
NAMCr is now returning 180 predictors. Thank you!
