### ISSUE TITLE
Error with optional Arguments

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/NAMCr#3]
Trying to run the new sampleMetrics API endpoint (endpoint number 34 in the CLI). I get the following error:

I entered 3 for the translation (OTUCode 2) and 300 for the fixed count. When I typed 1 in preparation for typing some sample IDs, I got the following error:

<img width="608" alt="Screen Shot 2021-06-29 at 2 59 58 PM" src="https://user-images.githubusercontent.com/8645379/123873120-dc020980-d8ea-11eb-8d5e-ea43e91ff970.png">

**Comment by David-Fowler** [comment]
I'll include this in the next push.
