### ISSUE TITLE
boxInfo and modelInfo error

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/NAMCr#31]
[Original issue](https://github.com/namc-utah/namc-bug-db/issues/761) from @Feldspar5:

the following endpoints are returning this error:

```
Error: 4.17: syntax error, unexpected }
```

boxInfo using:

```
result = query(
api_endpoint = "boxInfo",
args = list(boxId = 2098)
)
```

and modelInfo using

```
 result = query(
                         api_endpoint = "modelInfo",
                         args = list(modelId = 3)
          )
```

**Comment by Feldspar5** [comment]
I started receiving this error again this morning (it was working as of last night).  I will continue trying in case it is an AWS/sleeping issue.


result = query(
		api_endpoint = "modelInfo",
		args = list(modelId = 4)
	)


Retrieving data: Error: 4.17: syntax error, unexpected }

**Comment by Feldspar5** [comment]
Issue has resolved
