### ISSUE TITLE
How to enter lists in R?

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/NAMCr#4]
@David-Fowler can you help me format the following query please. 

The sampleMetrics endpoint takes three arguments:

* translation ID (I am trying ID 3 which refers to OTUCode2)
* fixed count (I am using 300)
* One of the following:
    *  list of sample IDs
    * list of box IDs
    * list of project IDs

How do I format the following with a single sample ID?

```R
NAMCr::query('sampleMetrics',list(3,300, sampleIds:list(164638)))
```

**Comment by David-Fowler** [comment]
This would be the required syntax for that query:

`data = NAMCr::query('sampleMetrics', list(translationId=3, fixedCount=300, sampleIds=c(164638)))`
or
`data = NAMCr::query('sampleMetrics', list(translationId=3, fixedCount=300, sampleIds=164638))`

Comma separate additional sampleId values in the `c(...)` array if desired like in the first line above. Single values can skip the `c(...)` syntax completely.

**Comment by David-Fowler** [comment]
Added a note to add an enhancement to make this less of an issue for users in the future.

#5

**Comment by philipbaileynar** [comment]
The syntax @David-Fowler provided works.

<img width="1211" alt="Screen Shot 2021-06-30 at 11 07 31 AM" src="https://user-images.githubusercontent.com/8645379/124010185-600fcc00-d993-11eb-98b1-efa9175304a7.png">
