### ISSUE TITLE
How to specify boolean values in R?

### ISSUE THREAD

**Issue by philipbaileynar** [namc-utah/NAMCr#9]
@courtwrightj01 is trying to make the following call:

```R
NAMCr::save("createProject",projectName="Intermittent stream",description="Jennifers work with Chuck to develop OE and MMI for intermittent streams") 
```

How should she specify the boolean `isPrivate` argument? She is getting “expected type Boolean, found FALSE".

**Comment by David-Fowler** [comment]
Boolean API parameters accept R boolean values (i.e. TRUE or FALSE) as well as 1 and 0.

`NAMCr::save("createProject", projectName="testProject2", isPrivate=TRUE, description="testing R API code")`

I think I just found an issue though for false boolean values where they might not be formatted properly. I will include a fix for this tonight  #10.
